Repository atlp-rwanda/e-comm-team-amigos-bn, pull requests merged in 2023-03, with the labels that each got.

#5 #184581166 Integrate circleCI and add build status in README
  .circleci/config.yml
  README.md
  package-lock.json
Labels: enhancement

#10 #184581170 Setup Docker for Backend Application
  .dockerignore
  .env.example
  Dockerfile
  README.md
  docker-compose.yml
  package.json
  src/app.js
  src/controllers/index.js
Labels: Ready for review

#13 #184581172 User Sign Up
  .env.example
  .gitignore
  README.md
  package-lock.json
  package.json
  src/app.js
  src/config.js
  src/controllers/authentication.js
  src/controllers/index.js
  src/database/migrations/20230302104214-create-user.js
  src/database/migrations/20230302105150-create-proflie.js
  src/database/models/index.js
  src/database/models/proflie.js
  src/database/models/user.js
  src/database/seeders/20230302105921-User.js
  src/database/seeders/20230302105929-Profile.js
  src/docs/auth.doc.js
  src/docs/index.js
  src/helpers/generateToken.js
  src/helpers/index.js
  src/index.js
  src/middleware/authValidation.js
  src/middleware/index.js
  src/middleware/user.js
  src/middleware/verifyToken.js
  src/routes/auth/index.js
  src/routes/index.js
  src/routes/user.js
  src/tests/auth.test.js
Labels: Ready for review

#16 #184581175 User Login feature
  package.json
  src/controllers/authentication.js
  src/docs/auth.doc.js
  src/middleware/authValidation.js
  src/routes/auth/index.js
  src/routes/user.js
  src/tests/auth.test.js
Labels: Ready for review

#19 #184581173 Send Verification email
  package-lock.json
  package.json
  src/controllers/authentication.js
  src/docs/auth.doc.js
  src/helpers/sendMail.js
  src/middleware/authValidation.js
  src/routes/auth/index.js
  src/tests/auth.test.js
Labels: Ready for review

#17 #184581176 Sign with Google
  .dockerignore
  .env.example
  .gitignore
  docker-compose.yml
  package-lock.json
  package.json
  src/app.js
  src/config.js
  src/controllers/authentication.js
  src/controllers/token.controller.js
  src/database/models/index.js
  src/database/models/user.js
  src/database/seeders/20230302105921-User.js
  src/docs/google-sign.doc.js
  src/docs/index.js
  src/helpers/google.oath.js
  src/routes/token.routes.js
  src/tests/auth.test.js
  src/tests/google-sign.test.js
Labels: Ready for review

#21 #184581183 Update password
  package-lock.json
  src/controllers/authentication.js
  src/database/seeders/20230302105921-User.js
  src/docs/auth.doc.js
  src/middleware/verifyToken.js
  src/routes/auth/index.js
  src/tests/auth.test.js
Labels: Ready for review

#26 #184581188 A User Should be able to list all Items
  .eslintignore
  .gitignore
  package-lock.json
  package.json
  src/app.js
  src/config.js
  src/controllers/authentication.js
  src/controllers/product.controller.js
  src/database/migrations/20230316091858-create-product.js
  src/database/models/product.js
  src/database/models/user.js
  src/database/seeders/20230302105921-User.js
  src/docs/product.doc.js
  src/routes/index.js
  src/routes/product.routes.js
  src/routes/products/product.js
  src/tests/auth.test.js
  src/tests/product.test.js
  src/validations/product.validator.js
Labels: Ready for review

#25 #184581184 create product
  package-lock.json
  package.json
  src/controllers/authentication.js
  src/controllers/index.js
  src/controllers/product.controller.js
  src/database/migrations/20230315143637-modify-user.js
  src/database/seeders/20230302105921-User.js
  src/docs/auth.doc.js
  src/docs/index.js
  src/docs/product.doc.js
  src/middleware/authValidation.js
  src/middleware/verifyToken.js
  src/routes/auth/index.js
  src/routes/product.routes.js
  src/routes/products/product.js
  src/tests/product.test.js
  src/validations/product.validator.js
Labels: Ready for review

#22 #184581182 set user roles or permissions
  .DS_Store
  README.md
  src/app.js
  src/controllers/authentication.js
  src/controllers/roles.js
  src/database/migrations/20230315184306-role.js
  src/database/migrations/20230315185600-permission.js
  src/database/migrations/20230315185837-user-role.js
  src/database/migrations/20230315194710-role-permission.js
  src/database/models/permissions.js
  src/database/models/role.js
  src/database/models/rolePermissions.js
  src/database/models/user.js
  src/database/models/userRole.js
  src/database/seeders/20230315200319-role.js
  src/database/seeders/20230315201156-permission.js
  src/docs/role.doc.js
  src/middleware/roleValidation.js
  src/routes/index.js
  src/routes/roles/index.js
  src/tests/auth.test.js
  src/tests/roles.test.js
Labels: documentation, WIP, Ready for review

#32 #184581180 Update User Profile
  src/app.js
  src/config.js
  src/controllers/authentication.js
  src/controllers/index.js
  src/controllers/user.js
  src/database/migrations/20230312135251-Users.js
  src/database/migrations/20230316212347-updateUserRelation.js
  src/database/models/index.js
  src/database/models/product.js
  src/database/models/user.js
  src/database/seeders/20230302105921-User.js
  src/docs/auth.doc.js
  src/docs/index.js
  src/docs/profile.doc.js
  src/middleware/user.js
  src/middleware/verifyToken.js
  src/routes/index.js
  src/routes/user/index.js
  src/tests/auth.test.js
  src/tests/google-sign.test.js
  src/tests/product.test.js
  src/tests/profile.test.js
  src/tests/roles.test.js
Labels: Ready for review

#37 #184581188 A User Should be able to list all Items
  src/config.js
  src/controllers/authentication.js
  src/controllers/product.controller.js
  src/database/migrations/20230315143637-modify-user.js
  src/docs/auth.doc.js
  src/docs/product.doc.js
  src/middleware/verifyToken.js
  src/routes/products/product.js
  src/tests/auth.test.js
  src/tests/product.test.js
  src/tests/roles.test.js
Labels: Ready for review

#39 #184581204 Users Public Chat Space
  package-lock.json
  package.json
  src/app.js
  src/controllers/chat.controller.js
  src/database/migrations/20230317213206-create-chat.js
  src/database/models/chat.js
  src/database/models/user.js
  src/docs/chat.doc.js
  src/helpers/messageHelper.js
  src/helpers/verifySocketToken.js
  src/index.js
  src/middleware/socketAuth.js
  src/routes/chat.route.js
  src/routes/index.js
  src/tests/chat.test.js
Labels: Ready for review

#40 #184581196 Search Product
  .eslintignore
  package-lock.json
  src/app.js
  src/config.js
  src/controllers/authentication.js
  src/controllers/chat.controller.js
  src/controllers/product.controller.js
  src/controllers/roles.js
  src/controllers/token.controller.js
  src/database/migrations/20230315184306-role.js
  src/database/migrations/20230315185600-permission.js
  src/database/migrations/20230315185837-user-role.js
  src/database/migrations/20230315194710-role-permission.js
  src/database/migrations/20230316091858-create-product.js
  src/database/migrations/20230316212347-updateUserRelation.js
  src/database/migrations/20230317213206-create-chat.js
  src/database/models/chat.js
  src/database/models/index.js
  src/database/models/permissions.js
  src/database/models/product.js
  src/database/seeders/20230302105921-User.js
  src/database/seeders/20230315200319-role.js
  src/docs/auth.doc.js
  src/docs/chat.doc.js
  src/docs/google-sign.doc.js
  src/docs/index.js
  src/docs/product.doc.js
  src/docs/role.doc.js
  src/helpers/createotp.js
  src/helpers/generateToken.js
  src/helpers/google.oath.js
  src/helpers/messageHelper.js
  src/helpers/sendResetPasswordEmail.js
  src/helpers/verifySocketToken.js
  src/index.js
  src/middleware/authValidation.js
  src/middleware/socketAuth.js
  src/middleware/verifyToken.js
  src/routes/auth/index.js
  src/routes/chat.route.js
  src/routes/index.js
  src/routes/product.routes.js
  src/routes/products/product.js
  src/routes/roles/index.js
  src/routes/token.routes.js
  src/routes/user/index.js
  src/tests/app.test.js
  src/tests/auth.test.js
  src/tests/chat.test.js
  src/tests/google-sign.test.js
  src/tests/product.test.js
  src/tests/profile.test.js
  src/tests/roles.test.js
  src/validations/product.validator.js
Labels: Ready for review

#36 #184581192 Add items to cart
  package-lock.json
  src/app.js
  src/controllers/cart.controller.js
  src/controllers/token.controller.js
  src/database/seeders/20230323123905-product-create.js
  src/docs/cart.doc.js
  src/routes/cart.routes.js
  src/tests/cart.test.js
  src/validations/cart.validator.js
  src/validations/product.validator.js
Labels: Ready for review

#45 #184769261 Remove passwords in response's body
  src/controllers/roles.js
  src/controllers/user.js
  src/database/migrations/20230317064446-Users.js
  src/docs/product.doc.js
  src/tests/product.test.js
Labels: Ready for review

#43 #184581194 retrieve cart from buyer's session
  package-lock.json
  package.json
  src/app.js
  src/controllers/cart.controller.js
  src/database/migrations/20230217064336-Users.js
  src/database/migrations/20230316212347-updateUserRelation.js
  src/database/migrations/20230317064446-Users.js
  src/database/seeders/20230322212957-create-product.js
  src/database/seeders/20230323123905-product-create.js
  src/docs/cart.doc.js
  src/routes/cart.routes.js
  src/tests/cart.test.js
Labels: Ready for review

#24 #184581189 update products in seller collection
  README.md
  package.json
  src/app.js
  src/controllers/authentication.js
  src/controllers/product.controller.js
  src/controllers/token.controller.js
  src/database/migrations/20230317064446-Users.js
  src/database/migrations/20230318212347-updateUserRelation.js
  src/docs/components/product.schema.doc.js
  src/docs/google-sign.doc.js
  src/docs/index.js
  src/docs/product.doc.js
  src/middleware/authValidation.js
  src/middleware/verifyToken.js
  src/routes/products/product.js
  src/routes/user/index.js
  src/tests/auth.test.js
  src/tests/cart.test.js
  src/tests/google-sign.test.js
  src/tests/product.test.js
  src/validations/product.validator.js
Labels: Ready for review

#41 #184581193 update cart in session
  package-lock.json
  src/controllers/cart.controller.js
  src/database/migrations/20230317064446-Users.js
  src/database/seeders/20230318061634-product.js
  src/database/seeders/20230322212957-create-product.js
  src/docs/cart.doc.js
  src/routes/cart.routes.js
  src/tests/cart.test.js
Labels: Ready for review

#46 #184581195 buyer should be able to clear their cart
  src/app.js
  src/controllers/cart.controller.js
  src/docs/product.doc.js
  src/middleware/verifyToken.js
  src/routes/cart.routes.js
  src/routes/index.js
  src/tests/cart.test.js
  src/tests/product.test.js
Labels: Ready for review

#44 #184581190 Allow buyer to add products to their wish list
  package-lock.json
  package.json
  src/controllers/wishlist.controller.js
  src/database/migrations/20230327091529-Wishlist.js
  src/database/models/wishlist.js
  src/database/seeders/20230322212957-create-product.js
  src/docs/product.doc.js
  src/docs/wishlist.doc.js
  src/routes/index.js
  src/routes/wishlist/index.js
  src/tests/wishlist.test.js
Labels: Ready for review

#47 #184797859: Implement pagination support for all get all endpoints
  src/controllers/product.controller.js
  src/controllers/roles.js
  src/database/seeders/20230322212957-create-product.js
  src/tests/product.test.js
  src/tests/roles.test.js
Labels: Ready for review

#51 #184581197 Get and Update order status information
  package-lock.json
  src/app.js
  src/controllers/order.controller.js
  src/database/migrations/20230329060244-create-order.js.js
  src/database/migrations/20230329060403-create-order-product.js
  src/database/models/order.js
  src/database/models/orderProduct.js
  src/database/models/product.js
  src/database/models/user.js
  src/database/seeders/20230328090843-create-order.js
  src/docs/order.doc.js
  src/routes/index.js
  src/routes/order.routes.js
  src/tests/cart.test.js
  src/tests/order.test.js
Labels: Ready for review

#52 #184581191 Review, rating and feedback on bought product
  src/controllers/product.controller.js
  src/controllers/review.controller.js
  src/database/migrations/20230328074506-create-review.js
  src/database/models/reviews.js
  src/docs/product.doc.js
  src/docs/review.doc.js
  src/routes/Review/review.js
  src/routes/index.js
  src/routes/product.routes.js
  src/routes/products/product.js
  src/tests/review.test.js
  src/validations/review.validation.js
Labels: Ready for review

#53 #184797864 Admin should be able to CRUD users
  src/controllers/admin.user.controller.js
  src/database/seeders/20230302105921-User.js
  src/docs/admin.doc.js
  src/docs/product.doc.js
  src/middleware/verifyToken.js
  src/routes/admin/index.js
  src/routes/index.js
  src/routes/products/product.js
  src/tests/auth.test.js
  src/tests/product.test.js
  src/tests/users.test.js
  src/tests/view_item.test.js
Labels: Ready for review

#54 #184797860 Implement custom database seeder script
  .DS_Store
  .gitignore
  package.json
  src/database/migrations/20230329060244-create-order.js
  src/database/migrations/20230329060244-create-order.js.js
  src/database/models/order.js
  src/database/models/orderProduct.js
  src/database/seeders/index.js
  src/docs/product.doc.js
  src/helpers/generateRandomNumber.js
Labels: Ready for review

#55 #184797861 Place Order
  .prettierrc
  src/app.js
  src/controllers/order.controller.js
  src/controllers/product.controller.js
  src/database/models/index.js
  src/database/models/order.js
  src/database/models/user.js
  src/database/seeders/20230302105921-User.js
  src/database/seeders/20230322212957-create-product.js
  src/database/seeders/20230328090843-create-order.js
  src/database/seeders/20230330072036-demo-orders.js
  src/docs/order.doc.js
  src/middleware/verifyToken.js
  src/routes/index.js
  src/routes/order.routes.js
  src/routes/products/product.js
  src/tests/auth.test.js
  src/tests/cart.test.js
  src/tests/chat.test.js
  src/tests/google-sign.test.js
  src/tests/order.test.js
  src/tests/product.test.js
  src/tests/profile.test.js
  src/tests/roles.test.js
  src/tests/view_item.test.js
  src/tests/wishlist.test.js
Labels: Ready for review
